name: chengwujunxiang
on:
  workflow_dispatch:

  schedule:
    - cron: '1 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengwujunxiang
        env:
          gn22: ${{ secrets.gn22 }}
        run: |
          printf '%s' "$gn22" | jq -r .lr2984 | /bin/bash
          printf '%s' "$e856" | jq -r .n771 | /bin/bash
          echo $kb5898 | jq -r .zutfe5257 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: g8TsTfZp
          path: "*.zip"
          retention-days: 1
